export const keys = [
    {letter:'Ёё', value: 'ё'},
    {letter:'0', value: '0'},
    {letter:'1', value: '1'},
    {letter:'2', value: '2'},
    {letter:'3', value: '3'},
    {letter:'4', value: '4'},
    {letter:'5', value: '5'},
    {letter:'6', value: '6'},
    {letter:'7', value: '7'},
    {letter:'8', value: '8'},
    {letter:'9', value: '9'},
    {letter:'-', value: '-'},
    {letter:'=', value: '='},
    {letter:'Backspace', value: 'Backspace'},

    {letter:'Tab', value: 'Tab'},
    {letter:'Йй', value: 'й'},
    {letter:'Цц', value: 'ц'},
    {letter:'Уу', value: 'у'},
    {letter:'Кк', value: 'к'},
    {letter:'Ее', value: 'е'},
    {letter:'Нн', value: 'н'},
    {letter:'Гг', value: 'г'},
    {letter:'Шш', value: 'ш'},
    {letter:'Щщ', value: 'щ'},
    {letter:'Зз', value: 'з'},
    {letter:'Хх', value: 'х'},
    {letter:'Ъъ', value: 'ъ'},
    {letter:'\\', value: '\\'},

    {letter:'CapsLock', value: 'CapsLock'},
    {letter:'Фф', value: 'ф'},
    {letter:'Ыы', value: 'ы'},
    {letter:'Вв', value: 'в'},
    {letter:'Аа', value: 'а'},
    {letter:'Пп', value: 'п'},
    {letter:'Рр', value: 'р'},
    {letter:'Оо', value: 'о'},
    {letter:'Лл', value: 'л'},
    {letter:'Дд', value: 'д'},
    {letter:'Жж', value: 'ж'},
    {letter:'Ээ', value: 'э'},
    {letter:'Enter', value: 'Enter'},

    {letter:'Shift', value: 'Shift'},
    {letter:'Яя', value: 'я'},
    {letter:'Чч', value: 'ч'},
    {letter:'Сс', value: 'с'},
    {letter:'Мм', value: 'м'},
    {letter:'Ии', value: 'и'},
    {letter:'Тт', value: 'т'},
    {letter:'Ьь', value: 'ь'},
    {letter:'Бб', value: 'б'},
    {letter:'Юю', value: 'ю'},
    {letter:'.', value: '.'},
    {letter:'Shift', value: 'Shift'},

    {letter:'Control', value: 'Ctrl'},
    {letter:'Fn', value: 'Fn'},
    {letter:'Meta', value: 'Win'},
    {letter:'Alt', value: 'Alt'},
    {letter:' ', value: ''},
    {letter:'Alt', value: 'Alt'},
    {letter:'Control', value: 'Ctrl'}
];